// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/gin-mam/backend/internal/domain/catalog/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCatalog mocks base method.
func (m *MockRepository) CreateCatalog(ctx context.Context, row *model.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCatalog", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCatalog indicates an expected call of CreateCatalog.
func (mr *MockRepositoryMockRecorder) CreateCatalog(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCatalog", reflect.TypeOf((*MockRepository)(nil).CreateCatalog), ctx, row)
}

// DeleteCatalog mocks base method.
func (m *MockRepository) DeleteCatalog(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCatalog", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCatalog indicates an expected call of DeleteCatalog.
func (mr *MockRepositoryMockRecorder) DeleteCatalog(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCatalog", reflect.TypeOf((*MockRepository)(nil).DeleteCatalog), ctx, tenantID, id)
}

// DeleteConfigsNotInKeys mocks base method.
func (m *MockRepository) DeleteConfigsNotInKeys(ctx context.Context, tenantID, catalogID string, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfigsNotInKeys", ctx, tenantID, catalogID, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfigsNotInKeys indicates an expected call of DeleteConfigsNotInKeys.
func (mr *MockRepositoryMockRecorder) DeleteConfigsNotInKeys(ctx, tenantID, catalogID, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigsNotInKeys", reflect.TypeOf((*MockRepository)(nil).DeleteConfigsNotInKeys), ctx, tenantID, catalogID, keys)
}

// GetCatalogByID mocks base method.
func (m *MockRepository) GetCatalogByID(ctx context.Context, tenantID, id string) (*model.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCatalogByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*model.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCatalogByID indicates an expected call of GetCatalogByID.
func (mr *MockRepositoryMockRecorder) GetCatalogByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalogByID", reflect.TypeOf((*MockRepository)(nil).GetCatalogByID), ctx, tenantID, id)
}

// ListCatalogs mocks base method.
func (m *MockRepository) ListCatalogs(ctx context.Context, tenantID string) ([]model.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCatalogs", ctx, tenantID)
	ret0, _ := ret[0].([]model.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCatalogs indicates an expected call of ListCatalogs.
func (mr *MockRepositoryMockRecorder) ListCatalogs(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCatalogs", reflect.TypeOf((*MockRepository)(nil).ListCatalogs), ctx, tenantID)
}

// ListConfigs mocks base method.
func (m *MockRepository) ListConfigs(ctx context.Context, tenantID, catalogID string) ([]model.CatalogConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigs", ctx, tenantID, catalogID)
	ret0, _ := ret[0].([]model.CatalogConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigs indicates an expected call of ListConfigs.
func (mr *MockRepositoryMockRecorder) ListConfigs(ctx, tenantID, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigs", reflect.TypeOf((*MockRepository)(nil).ListConfigs), ctx, tenantID, catalogID)
}

// UpdateCatalog mocks base method.
func (m *MockRepository) UpdateCatalog(ctx context.Context, row *model.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCatalog", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCatalog indicates an expected call of UpdateCatalog.
func (mr *MockRepositoryMockRecorder) UpdateCatalog(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCatalog", reflect.TypeOf((*MockRepository)(nil).UpdateCatalog), ctx, row)
}

// UpsertConfig mocks base method.
func (m *MockRepository) UpsertConfig(ctx context.Context, row *model.CatalogConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertConfig", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertConfig indicates an expected call of UpsertConfig.
func (mr *MockRepositoryMockRecorder) UpsertConfig(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertConfig", reflect.TypeOf((*MockRepository)(nil).UpsertConfig), ctx, row)
}
