// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock/service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	catalog "github.com/gin-mam/backend/internal/domain/catalog"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BatchUpdateConfig mocks base method.
func (m *MockService) BatchUpdateConfig(ctx context.Context, catalogID string, items []catalog.ConfigItemInput) ([]catalog.ConfigVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateConfig", ctx, catalogID, items)
	ret0, _ := ret[0].([]catalog.ConfigVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateConfig indicates an expected call of BatchUpdateConfig.
func (mr *MockServiceMockRecorder) BatchUpdateConfig(ctx, catalogID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateConfig", reflect.TypeOf((*MockService)(nil).BatchUpdateConfig), ctx, catalogID, items)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, in catalog.CreateInput) (*catalog.CatalogVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*catalog.CatalogVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, in)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// ListConfig mocks base method.
func (m *MockService) ListConfig(ctx context.Context, catalogID string) ([]catalog.ConfigVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfig", ctx, catalogID)
	ret0, _ := ret[0].([]catalog.ConfigVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfig indicates an expected call of ListConfig.
func (mr *MockServiceMockRecorder) ListConfig(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfig", reflect.TypeOf((*MockService)(nil).ListConfig), ctx, catalogID)
}

// Tree mocks base method.
func (m *MockService) Tree(ctx context.Context) ([]catalog.TreeNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree", ctx)
	ret0, _ := ret[0].([]catalog.TreeNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tree indicates an expected call of Tree.
func (mr *MockServiceMockRecorder) Tree(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockService)(nil).Tree), ctx)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, id string, in catalog.UpdateInput) (*catalog.CatalogVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, in)
	ret0, _ := ret[0].(*catalog.CatalogVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, id, in)
}
