// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/gin-mam/backend/internal/domain/workflow/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateDef mocks base method.
func (m *MockRepository) CreateDef(ctx context.Context, def *model.WorkflowDef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDef", ctx, def)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDef indicates an expected call of CreateDef.
func (mr *MockRepositoryMockRecorder) CreateDef(ctx, def any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDef", reflect.TypeOf((*MockRepository)(nil).CreateDef), ctx, def)
}

// CreateInstance mocks base method.
func (m *MockRepository) CreateInstance(ctx context.Context, inst *model.WorkflowInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, inst)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockRepositoryMockRecorder) CreateInstance(ctx, inst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockRepository)(nil).CreateInstance), ctx, inst)
}

// CreateInstanceLevelUsers mocks base method.
func (m *MockRepository) CreateInstanceLevelUsers(ctx context.Context, rows []model.WorkflowInstanceLevelUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstanceLevelUsers", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInstanceLevelUsers indicates an expected call of CreateInstanceLevelUsers.
func (mr *MockRepositoryMockRecorder) CreateInstanceLevelUsers(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceLevelUsers", reflect.TypeOf((*MockRepository)(nil).CreateInstanceLevelUsers), ctx, rows)
}

// CreateLevelUsers mocks base method.
func (m *MockRepository) CreateLevelUsers(ctx context.Context, rows []model.WorkflowLevelUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLevelUsers", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLevelUsers indicates an expected call of CreateLevelUsers.
func (mr *MockRepositoryMockRecorder) CreateLevelUsers(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLevelUsers", reflect.TypeOf((*MockRepository)(nil).CreateLevelUsers), ctx, rows)
}

// CreateOperate mocks base method.
func (m *MockRepository) CreateOperate(ctx context.Context, row *model.WorkflowOperate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperate", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOperate indicates an expected call of CreateOperate.
func (mr *MockRepositoryMockRecorder) CreateOperate(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperate", reflect.TypeOf((*MockRepository)(nil).CreateOperate), ctx, row)
}

// DeleteInstance mocks base method.
func (m *MockRepository) DeleteInstance(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockRepositoryMockRecorder) DeleteInstance(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockRepository)(nil).DeleteInstance), ctx, tenantID, id)
}

// GetDefByID mocks base method.
func (m *MockRepository) GetDefByID(ctx context.Context, tenantID, id string) (*model.WorkflowDef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*model.WorkflowDef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefByID indicates an expected call of GetDefByID.
func (mr *MockRepositoryMockRecorder) GetDefByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefByID", reflect.TypeOf((*MockRepository)(nil).GetDefByID), ctx, tenantID, id)
}

// GetInstanceByID mocks base method.
func (m *MockRepository) GetInstanceByID(ctx context.Context, tenantID, id string) (*model.WorkflowInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*model.WorkflowInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceByID indicates an expected call of GetInstanceByID.
func (mr *MockRepositoryMockRecorder) GetInstanceByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceByID", reflect.TypeOf((*MockRepository)(nil).GetInstanceByID), ctx, tenantID, id)
}

// IsUserAssigneeAtLevel mocks base method.
func (m *MockRepository) IsUserAssigneeAtLevel(ctx context.Context, tenantID, instanceID string, level int, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAssigneeAtLevel", ctx, tenantID, instanceID, level, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserAssigneeAtLevel indicates an expected call of IsUserAssigneeAtLevel.
func (mr *MockRepositoryMockRecorder) IsUserAssigneeAtLevel(ctx, tenantID, instanceID, level, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAssigneeAtLevel", reflect.TypeOf((*MockRepository)(nil).IsUserAssigneeAtLevel), ctx, tenantID, instanceID, level, userID)
}

// ListAllInstances mocks base method.
func (m *MockRepository) ListAllInstances(ctx context.Context, tenantID string, page, pageSize int) ([]model.WorkflowInstance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllInstances", ctx, tenantID, page, pageSize)
	ret0, _ := ret[0].([]model.WorkflowInstance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllInstances indicates an expected call of ListAllInstances.
func (mr *MockRepositoryMockRecorder) ListAllInstances(ctx, tenantID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllInstances", reflect.TypeOf((*MockRepository)(nil).ListAllInstances), ctx, tenantID, page, pageSize)
}

// ListDefs mocks base method.
func (m *MockRepository) ListDefs(ctx context.Context, tenantID string, page, pageSize int) ([]model.WorkflowDef, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefs", ctx, tenantID, page, pageSize)
	ret0, _ := ret[0].([]model.WorkflowDef)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDefs indicates an expected call of ListDefs.
func (mr *MockRepositoryMockRecorder) ListDefs(ctx, tenantID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefs", reflect.TypeOf((*MockRepository)(nil).ListDefs), ctx, tenantID, page, pageSize)
}

// ListInstancesAssignedToUser mocks base method.
func (m *MockRepository) ListInstancesAssignedToUser(ctx context.Context, tenantID, userID string, page, pageSize int) ([]model.WorkflowInstance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstancesAssignedToUser", ctx, tenantID, userID, page, pageSize)
	ret0, _ := ret[0].([]model.WorkflowInstance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInstancesAssignedToUser indicates an expected call of ListInstancesAssignedToUser.
func (mr *MockRepositoryMockRecorder) ListInstancesAssignedToUser(ctx, tenantID, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstancesAssignedToUser", reflect.TypeOf((*MockRepository)(nil).ListInstancesAssignedToUser), ctx, tenantID, userID, page, pageSize)
}

// ListInstancesAuditedBy mocks base method.
func (m *MockRepository) ListInstancesAuditedBy(ctx context.Context, tenantID, userID string, page, pageSize int) ([]model.WorkflowInstance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstancesAuditedBy", ctx, tenantID, userID, page, pageSize)
	ret0, _ := ret[0].([]model.WorkflowInstance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInstancesAuditedBy indicates an expected call of ListInstancesAuditedBy.
func (mr *MockRepositoryMockRecorder) ListInstancesAuditedBy(ctx, tenantID, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstancesAuditedBy", reflect.TypeOf((*MockRepository)(nil).ListInstancesAuditedBy), ctx, tenantID, userID, page, pageSize)
}

// ListInstancesCreatedBy mocks base method.
func (m *MockRepository) ListInstancesCreatedBy(ctx context.Context, tenantID, userID string, page, pageSize int) ([]model.WorkflowInstance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstancesCreatedBy", ctx, tenantID, userID, page, pageSize)
	ret0, _ := ret[0].([]model.WorkflowInstance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInstancesCreatedBy indicates an expected call of ListInstancesCreatedBy.
func (mr *MockRepositoryMockRecorder) ListInstancesCreatedBy(ctx, tenantID, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstancesCreatedBy", reflect.TypeOf((*MockRepository)(nil).ListInstancesCreatedBy), ctx, tenantID, userID, page, pageSize)
}

// ListLevelUsersByDefID mocks base method.
func (m *MockRepository) ListLevelUsersByDefID(ctx context.Context, tenantID, defID string) ([]model.WorkflowLevelUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLevelUsersByDefID", ctx, tenantID, defID)
	ret0, _ := ret[0].([]model.WorkflowLevelUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLevelUsersByDefID indicates an expected call of ListLevelUsersByDefID.
func (mr *MockRepositoryMockRecorder) ListLevelUsersByDefID(ctx, tenantID, defID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLevelUsersByDefID", reflect.TypeOf((*MockRepository)(nil).ListLevelUsersByDefID), ctx, tenantID, defID)
}

// UpdateInstance mocks base method.
func (m *MockRepository) UpdateInstance(ctx context.Context, inst *model.WorkflowInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", ctx, inst)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockRepositoryMockRecorder) UpdateInstance(ctx, inst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockRepository)(nil).UpdateInstance), ctx, inst)
}

// UpdateInstanceLevelUserStatus mocks base method.
func (m *MockRepository) UpdateInstanceLevelUserStatus(ctx context.Context, tenantID, instanceID string, level int, userID string, status int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceLevelUserStatus", ctx, tenantID, instanceID, level, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstanceLevelUserStatus indicates an expected call of UpdateInstanceLevelUserStatus.
func (mr *MockRepositoryMockRecorder) UpdateInstanceLevelUserStatus(ctx, tenantID, instanceID, level, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceLevelUserStatus", reflect.TypeOf((*MockRepository)(nil).UpdateInstanceLevelUserStatus), ctx, tenantID, instanceID, level, userID, status)
}
