// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock/service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	workflow "github.com/gin-mam/backend/internal/domain/workflow"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Audit mocks base method.
func (m *MockService) Audit(ctx context.Context, userID string, in workflow.AuditRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Audit", ctx, userID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Audit indicates an expected call of Audit.
func (mr *MockServiceMockRecorder) Audit(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Audit", reflect.TypeOf((*MockService)(nil).Audit), ctx, userID, in)
}

// CreateDef mocks base method.
func (m *MockService) CreateDef(ctx context.Context, in workflow.CreateDefInput) (*workflow.DefVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDef", ctx, in)
	ret0, _ := ret[0].(*workflow.DefVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDef indicates an expected call of CreateDef.
func (mr *MockServiceMockRecorder) CreateDef(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDef", reflect.TypeOf((*MockService)(nil).CreateDef), ctx, in)
}

// DefPage mocks base method.
func (m *MockService) DefPage(ctx context.Context, page, pageSize int) (*workflow.DefPageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefPage", ctx, page, pageSize)
	ret0, _ := ret[0].(*workflow.DefPageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefPage indicates an expected call of DefPage.
func (mr *MockServiceMockRecorder) DefPage(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefPage", reflect.TypeOf((*MockService)(nil).DefPage), ctx, page, pageSize)
}

// ListAll mocks base method.
func (m *MockService) ListAll(ctx context.Context, page, pageSize int) (*workflow.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, page, pageSize)
	ret0, _ := ret[0].(*workflow.PageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockServiceMockRecorder) ListAll(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockService)(nil).ListAll), ctx, page, pageSize)
}

// ListAssignedToMe mocks base method.
func (m *MockService) ListAssignedToMe(ctx context.Context, userID string, page, pageSize int) (*workflow.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssignedToMe", ctx, userID, page, pageSize)
	ret0, _ := ret[0].(*workflow.PageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssignedToMe indicates an expected call of ListAssignedToMe.
func (mr *MockServiceMockRecorder) ListAssignedToMe(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssignedToMe", reflect.TypeOf((*MockService)(nil).ListAssignedToMe), ctx, userID, page, pageSize)
}

// ListAuditedByMe mocks base method.
func (m *MockService) ListAuditedByMe(ctx context.Context, userID string, page, pageSize int) (*workflow.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditedByMe", ctx, userID, page, pageSize)
	ret0, _ := ret[0].(*workflow.PageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditedByMe indicates an expected call of ListAuditedByMe.
func (mr *MockServiceMockRecorder) ListAuditedByMe(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditedByMe", reflect.TypeOf((*MockService)(nil).ListAuditedByMe), ctx, userID, page, pageSize)
}

// ListCreatedByMe mocks base method.
func (m *MockService) ListCreatedByMe(ctx context.Context, userID string, page, pageSize int) (*workflow.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCreatedByMe", ctx, userID, page, pageSize)
	ret0, _ := ret[0].(*workflow.PageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCreatedByMe indicates an expected call of ListCreatedByMe.
func (mr *MockServiceMockRecorder) ListCreatedByMe(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCreatedByMe", reflect.TypeOf((*MockService)(nil).ListCreatedByMe), ctx, userID, page, pageSize)
}

// MultiAudit mocks base method.
func (m *MockService) MultiAudit(ctx context.Context, userID string, items []workflow.AuditRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiAudit", ctx, userID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// MultiAudit indicates an expected call of MultiAudit.
func (mr *MockServiceMockRecorder) MultiAudit(ctx, userID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiAudit", reflect.TypeOf((*MockService)(nil).MultiAudit), ctx, userID, items)
}

// Revoke mocks base method.
func (m *MockService) Revoke(ctx context.Context, userID string, instanceIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, userID, instanceIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockServiceMockRecorder) Revoke(ctx, userID, instanceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockService)(nil).Revoke), ctx, userID, instanceIDs)
}

// Submit mocks base method.
func (m *MockService) Submit(ctx context.Context, userID string, in workflow.SubmitRequest) (*workflow.InstanceVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, userID, in)
	ret0, _ := ret[0].(*workflow.InstanceVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockServiceMockRecorder) Submit(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockService)(nil).Submit), ctx, userID, in)
}
