// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock/service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	transcode "github.com/gin-mam/backend/internal/domain/transcode"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockService) CreateGroup(ctx context.Context, userID string, in transcode.CreateGroupInput) (*transcode.GroupVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, userID, in)
	ret0, _ := ret[0].(*transcode.GroupVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockServiceMockRecorder) CreateGroup(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockService)(nil).CreateGroup), ctx, userID, in)
}

// CreateTask mocks base method.
func (m *MockService) CreateTask(ctx context.Context, userID string, in transcode.CreateTaskInput) (*transcode.TaskVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, userID, in)
	ret0, _ := ret[0].(*transcode.TaskVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockServiceMockRecorder) CreateTask(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockService)(nil).CreateTask), ctx, userID, in)
}

// DeleteGroup mocks base method.
func (m *MockService) DeleteGroup(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockServiceMockRecorder) DeleteGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockService)(nil).DeleteGroup), ctx, id)
}

// GetTask mocks base method.
func (m *MockService) GetTask(ctx context.Context, id string) (*transcode.TaskVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(*transcode.TaskVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockServiceMockRecorder) GetTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockService)(nil).GetTask), ctx, id)
}

// GroupPage mocks base method.
func (m *MockService) GroupPage(ctx context.Context, page, pageSize int) (*transcode.GroupPageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupPage", ctx, page, pageSize)
	ret0, _ := ret[0].(*transcode.GroupPageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupPage indicates an expected call of GroupPage.
func (mr *MockServiceMockRecorder) GroupPage(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupPage", reflect.TypeOf((*MockService)(nil).GroupPage), ctx, page, pageSize)
}

// HandleCallback mocks base method.
func (m *MockService) HandleCallback(ctx context.Context, body []byte, signHeader string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, body, signHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockServiceMockRecorder) HandleCallback(ctx, body, signHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockService)(nil).HandleCallback), ctx, body, signHeader)
}

// TaskPage mocks base method.
func (m *MockService) TaskPage(ctx context.Context, page, pageSize int) (*transcode.TaskPageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskPage", ctx, page, pageSize)
	ret0, _ := ret[0].(*transcode.TaskPageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskPage indicates an expected call of TaskPage.
func (mr *MockServiceMockRecorder) TaskPage(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskPage", reflect.TypeOf((*MockService)(nil).TaskPage), ctx, page, pageSize)
}

// UpdateGroup mocks base method.
func (m *MockService) UpdateGroup(ctx context.Context, id string, in transcode.UpdateGroupInput) (*transcode.GroupVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, id, in)
	ret0, _ := ret[0].(*transcode.GroupVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockServiceMockRecorder) UpdateGroup(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockService)(nil).UpdateGroup), ctx, id, in)
}
