// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/gin-mam/backend/internal/domain/asset/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateAsset mocks base method.
func (m *MockRepository) CreateAsset(ctx context.Context, asset *model.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockRepositoryMockRecorder) CreateAsset(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockRepository)(nil).CreateAsset), ctx, asset)
}

// CreateAssetFile mocks base method.
func (m *MockRepository) CreateAssetFile(ctx context.Context, file *model.AssetFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssetFile", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAssetFile indicates an expected call of CreateAssetFile.
func (mr *MockRepositoryMockRecorder) CreateAssetFile(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssetFile", reflect.TypeOf((*MockRepository)(nil).CreateAssetFile), ctx, file)
}

// DeleteAsset mocks base method.
func (m *MockRepository) DeleteAsset(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsset", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAsset indicates an expected call of DeleteAsset.
func (mr *MockRepositoryMockRecorder) DeleteAsset(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsset", reflect.TypeOf((*MockRepository)(nil).DeleteAsset), ctx, tenantID, id)
}

// DeleteMetadataNotInKeys mocks base method.
func (m *MockRepository) DeleteMetadataNotInKeys(ctx context.Context, tenantID, assetID string, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetadataNotInKeys", ctx, tenantID, assetID, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMetadataNotInKeys indicates an expected call of DeleteMetadataNotInKeys.
func (mr *MockRepositoryMockRecorder) DeleteMetadataNotInKeys(ctx, tenantID, assetID, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetadataNotInKeys", reflect.TypeOf((*MockRepository)(nil).DeleteMetadataNotInKeys), ctx, tenantID, assetID, keys)
}

// GetAssetByID mocks base method.
func (m *MockRepository) GetAssetByID(ctx context.Context, tenantID, id string) (*model.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*model.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetByID indicates an expected call of GetAssetByID.
func (mr *MockRepositoryMockRecorder) GetAssetByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetByID", reflect.TypeOf((*MockRepository)(nil).GetAssetByID), ctx, tenantID, id)
}

// GetMasterFile mocks base method.
func (m *MockRepository) GetMasterFile(ctx context.Context, tenantID, assetID string) (*model.AssetFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterFile", ctx, tenantID, assetID)
	ret0, _ := ret[0].(*model.AssetFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterFile indicates an expected call of GetMasterFile.
func (mr *MockRepositoryMockRecorder) GetMasterFile(ctx, tenantID, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterFile", reflect.TypeOf((*MockRepository)(nil).GetMasterFile), ctx, tenantID, assetID)
}

// ListAssets mocks base method.
func (m *MockRepository) ListAssets(ctx context.Context, tenantID string, page, pageSize int, keyword string) ([]model.Asset, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssets", ctx, tenantID, page, pageSize, keyword)
	ret0, _ := ret[0].([]model.Asset)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAssets indicates an expected call of ListAssets.
func (mr *MockRepositoryMockRecorder) ListAssets(ctx, tenantID, page, pageSize, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssets", reflect.TypeOf((*MockRepository)(nil).ListAssets), ctx, tenantID, page, pageSize, keyword)
}

// ListMetadata mocks base method.
func (m *MockRepository) ListMetadata(ctx context.Context, tenantID, assetID string) ([]model.AssetMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetadata", ctx, tenantID, assetID)
	ret0, _ := ret[0].([]model.AssetMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetadata indicates an expected call of ListMetadata.
func (mr *MockRepositoryMockRecorder) ListMetadata(ctx, tenantID, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetadata", reflect.TypeOf((*MockRepository)(nil).ListMetadata), ctx, tenantID, assetID)
}

// UpdateAsset mocks base method.
func (m *MockRepository) UpdateAsset(ctx context.Context, asset *model.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsset", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAsset indicates an expected call of UpdateAsset.
func (mr *MockRepositoryMockRecorder) UpdateAsset(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsset", reflect.TypeOf((*MockRepository)(nil).UpdateAsset), ctx, asset)
}

// UpsertMetadata mocks base method.
func (m *MockRepository) UpsertMetadata(ctx context.Context, row *model.AssetMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMetadata", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMetadata indicates an expected call of UpsertMetadata.
func (mr *MockRepositoryMockRecorder) UpsertMetadata(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMetadata", reflect.TypeOf((*MockRepository)(nil).UpsertMetadata), ctx, row)
}
