// Code generated by MockGen. DO NOT EDIT.
// Source: upload.go
//
// Generated by this command:
//
//	mockgen -source=upload.go -destination=mock/upload_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	asset "github.com/gin-mam/backend/internal/domain/asset"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadService is a mock of UploadService interface.
type MockUploadService struct {
	ctrl     *gomock.Controller
	recorder *MockUploadServiceMockRecorder
	isgomock struct{}
}

// MockUploadServiceMockRecorder is the mock recorder for MockUploadService.
type MockUploadServiceMockRecorder struct {
	mock *MockUploadService
}

// NewMockUploadService creates a new mock instance.
func NewMockUploadService(ctrl *gomock.Controller) *MockUploadService {
	mock := &MockUploadService{ctrl: ctrl}
	mock.recorder = &MockUploadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadService) EXPECT() *MockUploadServiceMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockUploadService) Complete(ctx context.Context, in asset.UploadCompleteInput) (*asset.AssetVO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, in)
	ret0, _ := ret[0].(*asset.AssetVO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockUploadServiceMockRecorder) Complete(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockUploadService)(nil).Complete), ctx, in)
}

// Init mocks base method.
func (m *MockUploadService) Init(ctx context.Context, in asset.UploadInitInput) (*asset.UploadInitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, in)
	ret0, _ := ret[0].(*asset.UploadInitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Init indicates an expected call of Init.
func (mr *MockUploadServiceMockRecorder) Init(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockUploadService)(nil).Init), ctx, in)
}

// SaveChunk mocks base method.
func (m *MockUploadService) SaveChunk(ctx context.Context, in asset.UploadChunkInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChunk", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChunk indicates an expected call of SaveChunk.
func (mr *MockUploadServiceMockRecorder) SaveChunk(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChunk", reflect.TypeOf((*MockUploadService)(nil).SaveChunk), ctx, in)
}

// MockUploadSessionStore is a mock of UploadSessionStore interface.
type MockUploadSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockUploadSessionStoreMockRecorder
	isgomock struct{}
}

// MockUploadSessionStoreMockRecorder is the mock recorder for MockUploadSessionStore.
type MockUploadSessionStoreMockRecorder struct {
	mock *MockUploadSessionStore
}

// NewMockUploadSessionStore creates a new mock instance.
func NewMockUploadSessionStore(ctrl *gomock.Controller) *MockUploadSessionStore {
	mock := &MockUploadSessionStore{ctrl: ctrl}
	mock.recorder = &MockUploadSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadSessionStore) EXPECT() *MockUploadSessionStoreMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockUploadSessionStore) DeleteSession(ctx context.Context, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockUploadSessionStoreMockRecorder) DeleteSession(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockUploadSessionStore)(nil).DeleteSession), ctx, uploadID)
}

// GetChunk mocks base method.
func (m *MockUploadSessionStore) GetChunk(ctx context.Context, uploadID string, index int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunk", ctx, uploadID, index)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunk indicates an expected call of GetChunk.
func (mr *MockUploadSessionStoreMockRecorder) GetChunk(ctx, uploadID, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunk", reflect.TypeOf((*MockUploadSessionStore)(nil).GetChunk), ctx, uploadID, index)
}

// GetMeta mocks base method.
func (m *MockUploadSessionStore) GetMeta(ctx context.Context, uploadID string) (*asset.UploadMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeta", ctx, uploadID)
	ret0, _ := ret[0].(*asset.UploadMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeta indicates an expected call of GetMeta.
func (mr *MockUploadSessionStoreMockRecorder) GetMeta(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeta", reflect.TypeOf((*MockUploadSessionStore)(nil).GetMeta), ctx, uploadID)
}

// SaveChunk mocks base method.
func (m *MockUploadSessionStore) SaveChunk(ctx context.Context, uploadID string, index int, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChunk", ctx, uploadID, index, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChunk indicates an expected call of SaveChunk.
func (mr *MockUploadSessionStoreMockRecorder) SaveChunk(ctx, uploadID, index, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChunk", reflect.TypeOf((*MockUploadSessionStore)(nil).SaveChunk), ctx, uploadID, index, data)
}

// SaveMeta mocks base method.
func (m *MockUploadSessionStore) SaveMeta(ctx context.Context, uploadID string, meta asset.UploadMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMeta", ctx, uploadID, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMeta indicates an expected call of SaveMeta.
func (mr *MockUploadSessionStoreMockRecorder) SaveMeta(ctx, uploadID, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMeta", reflect.TypeOf((*MockUploadSessionStore)(nil).SaveMeta), ctx, uploadID, meta)
}
