// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock/service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	asset "github.com/gin-mam/backend/internal/domain/asset"
	search "github.com/gin-mam/backend/internal/domain/search"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ScheduleIndex mocks base method.
func (m *MockService) ScheduleIndex(doc asset.IndexDoc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ScheduleIndex", doc)
}

// ScheduleIndex indicates an expected call of ScheduleIndex.
func (mr *MockServiceMockRecorder) ScheduleIndex(doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleIndex", reflect.TypeOf((*MockService)(nil).ScheduleIndex), doc)
}

// SearchAsset mocks base method.
func (m *MockService) SearchAsset(ctx context.Context, in search.SearchInput) (*asset.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAsset", ctx, in)
	ret0, _ := ret[0].(*asset.PageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAsset indicates an expected call of SearchAsset.
func (mr *MockServiceMockRecorder) SearchAsset(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAsset", reflect.TypeOf((*MockService)(nil).SearchAsset), ctx, in)
}
